baseurl = "https://davi1990.github.io/OHBM2025-NFT-Course/"
canonifyURLs = true
relativeURLs = false
title = "OHBM 2025 - Neural Field Theory Course"
theme = "dimension"
languagecode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds = ["RSS"]

[params]
#logo = "fa-laptop"
logo = "fa-brain"

[[params.social]]
medium = "twitter"
icon = "twitter"
link = "https://twitter.com/DaveMomi"

[[params.social]]
medium = "github"
icon = "github"
link = "https://github.com/Davi1990"

[[params.social]]
medium = "website"
icon = "globe"
link = "https://davi1990.github.io/"

[[params.social]]
medium = "email"
icon = "envelope"
link = "mailto:dmomi@stanford.edu"

[languages]
[languages.en]
languageName = "English"
weight = 1
